getDir.o:getDir.c
	gcc -c getDir.c -I ./include
getFile.o: getFile.c
	gcc -c getFile.c -I ./include
getFileType.o: getFileType.c
	gcc -c getFileType.c -I ./include
moveDir.o: moveDir.c
	gcc -c moveDir.c -I ./include
moveFile: moveFile
	gcc -c moveFile.c -I ./include
removeDir.o: removeDir.c
	gcc -c removeDir.c -I ./include
removeFile.o: removeFile.c
	gcc -c removeFile.c -I ./include